name: gemini_flutter
description: "Conheça o Gemini, um aplicativo de chat inovador criado pela Google. Este aplicativo se baseia em tecnologia de ponta em inteligência artificial para proporcionar interações naturais e fluidas, sempre com respostas inteligentes e ajustadas às suas necessidades. Sua interface é extremamente intuitiva e de fácil utilização, prometendo revolucionar o modo como você comunica. O Gemini se destaca ainda pela sua habilidade de aprender a partir das suas conversas, se adaptando continuamente para oferecer uma experiência cada vez mais enriquecedora e sob medida. Ideal para trabalho, estudo ou entretenimento, o Gemini está preparado para ser o seu assistente virtual perfeito."

publish_to: 'none' 

version: 1.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dash_chat_2: ^0.0.19
  http: ^1.2.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  flutter_native_splash: ^2.3.10
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true